logger:
  level: 'info'

auth:
  signingKey: 'masha'
  accessTokenTTL: 12h

http:
  port: 8081

database:
  postgres:
    host: 'host.docker.internal'
    port: 5432
    user: 'postgres'
    password: 'admin'
    database: 'racket_rave'
