// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthLogin implements Auth_login operation.
//
// Login user.
//
// POST /api/auth/login
func (UnimplementedHandler) AuthLogin(ctx context.Context, req *AuthLoginReq) (r *LoginResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthRegister implements Auth_register operation.
//
// Register user.
//
// POST /api/auth/register
func (UnimplementedHandler) AuthRegister(ctx context.Context, req *AuthRegisterReq) (r *RegisterResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
