// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginOperation                   OperationName = "AuthLogin"
	AuthRegisterOperation                OperationName = "AuthRegister"
	CartAddRacketOperation               OperationName = "CartAddRacket"
	CartGetCartOperation                 OperationName = "CartGetCart"
	FeedbacksCreateFeedbackOperation     OperationName = "FeedbacksCreateFeedback"
	FeedbacksDeleteFeedbackOperation     OperationName = "FeedbacksDeleteFeedback"
	FeedbacksGetFeedbacksOperation       OperationName = "FeedbacksGetFeedbacks"
	OrdersCreateOrderOperation           OperationName = "OrdersCreateOrder"
	OrdersGetOrderOperation              OperationName = "OrdersGetOrder"
	OrdersGetOrdersOperation             OperationName = "OrdersGetOrders"
	OrdersUpdateOrderStatusOperation     OperationName = "OrdersUpdateOrderStatus"
	ProfileGetProfileOperation           OperationName = "ProfileGetProfile"
	RacketsCreateRacketOperation         OperationName = "RacketsCreateRacket"
	RacketsDeleteRacketOperation         OperationName = "RacketsDeleteRacket"
	RacketsGetRacketOperation            OperationName = "RacketsGetRacket"
	RacketsGetRacketFeedbacksOperation   OperationName = "RacketsGetRacketFeedbacks"
	RacketsGetRacketsOperation           OperationName = "RacketsGetRackets"
	RacketsUpdateRacketQuantityOperation OperationName = "RacketsUpdateRacketQuantity"
	RacketsUpdateRacketsCountOperation   OperationName = "RacketsUpdateRacketsCount"
	UsersChangeUserRoleOperation         OperationName = "UsersChangeUserRole"
	UsersGetUserOperation                OperationName = "UsersGetUser"
	UsersGetUsersOperation               OperationName = "UsersGetUsers"
)
