// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginOperation              OperationName = "AuthLogin"
	AuthRegisterOperation           OperationName = "AuthRegister"
	UserAddRacketOperation          OperationName = "UserAddRacket"
	UserCreateFeedbackOperation     OperationName = "UserCreateFeedback"
	UserCreateOrderOperation        OperationName = "UserCreateOrder"
	UserDeleteFeedbackOperation     OperationName = "UserDeleteFeedback"
	UserDeleteRacketOperation       OperationName = "UserDeleteRacket"
	UserGetCartOperation            OperationName = "UserGetCart"
	UserGetFeedbacksOperation       OperationName = "UserGetFeedbacks"
	UserGetProfileOperation         OperationName = "UserGetProfile"
	UserUpdateRacketsCountOperation OperationName = "UserUpdateRacketsCount"
)
